name: Deploy PR preview
permissions:
  contents: write
# Run workflow on every push to the master branch
on:
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 8.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
        include-prerelease: true

    # publishes Blazor project to the release-folderl

    #- name: Change base-tag in app.razor from / to CslyViz
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/CslyViz\/" \/>/g' BlazorVizView/App.razor
      
    - name: Publish .NET Core Project
      if: github.event.action != 'closed'
      run: dotnet publish CslyViz.csproj -c Release -o release 
    
    # changes the base-tag in index.html from '/' to 'CslyViz' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to CslyViz/pr-preview/pr-XXXX
      if: github.event.action != 'closed'
      run: sed -i 's/<base href="\/" \/>/<base href="\/CslyViz\/pr-preview\/pr-${{ github.event.number }}\/" \/>/g' release/wwwroot/index.html    
    - name: Change manifest url in index.html from / to /CslyViz/pr-preview/pr-XXXX
      if: github.event.action != 'closed'
      run: sed -i 's/<link href="manifest.webmanifest" rel="manifest" \/>/<link href="\/CslyViz\/pr-preview\/pr-${{ github.event.number }}\/manifest.webmanifest" rel="manifest" \/>/g' release/wwwroot/index.html
    - name: Change service-worker url in index.html from / to /CslyViz/pr-preview/pr-XXXX
      if: github.event.action != 'closed'
      run: sed -i 's/\/service-worker.js/\/CslyViz\/pr-preview\/pr-${{ github.event.number }}\/service-worker.js/g' release/wwwroot/index.html  
    - name: Change favicon url in index.html from / to /CslyViz/pr-preview/pr-XXXX
      if: github.event.action != 'closed'
      run: sed -i 's/href="favicon.png"/href="\/CslyViz\/pr-preview\/pr-${{ github.event.number }}\/favicon.png"/g' release/wwwroot/index.html 
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      if: github.event.action != 'closed'    
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      if: github.event.action != 'closed'    
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        token : ${{ secrets.PAGES_TOKEN }}
        source-dir: ./release/wwwroot  
    
