name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 7.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
        include-prerelease: true

    # publishes Blazor project to the release-folderl

    #- name: Change base-tag in app.razor from / to MyBlazorPwa
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/MyBlazorPwa\/" \/>/g' BlazorVizView/App.razor
      
    - name: Publish .NET Core Project
      run: dotnet publish BlazorVizView/BlazorVizView.csproj -c Release -o release 
    
    # changes the base-tag in index.html from '/' to 'MyBlazorPwa' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to MyBlazorPwa
      run: sed -i 's/<base href="\/" \/>/<base href="\/MyBlazorPwa\/" \/>/g' release/wwwroot/index.html    
    - name: Change manifest url in index.html from / to /MyBlazorPwa
      run: sed -i 's/<link href="manifest.webmanifest" rel="manifest" \/>/<link href="\/MyBlazorPwa\/manifest.webmanifest" rel="manifest" \/>/g' release/wwwroot/index.html
    - name: Change service-worker url in index.html from / to /MyBlazorPwa
      run: sed -i 's/\/service-worker.js/\/MyBlazorPwa\/service-worker.js/g' release/wwwroot/index.html  
    - name: Change favicon url in index.html from / to /MyBlazorPwa
      run: sed -i 's/href="favicon.png"/href="\/MyBlazorPwa\/favicon.png"/g' release/wwwroot/index.html 
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
